In [7]:
%timeit [j**3 for j in range(1,9)]

1.93 µs ± 108 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [2]:
import numpy as np

%timeit np.arange(1,9)**3

5.1 µs ± 221 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [11]:
x=[1,2,3,4]

y=np.array(x)

print(y,type(y))
print(y.ndim)

[1 2 3 4] <class 'numpy.ndarray'>
1


In [15]:
l=[]

for i in range(4):
    x=input("enter a word:- ")
    l.append(x)
y=np.array(l)
print(y)

enter a word:- 1
enter a word:- 2
enter a word:- 4
enter a word:- 5
['1' '2' '4' '5']


In [7]:
y=np.array([[[1,2,3],[2,3,4],[1,2,3]]])
print(y,type(y))
print(y.ndim)

[[[1 2 3]
  [2 3 4]
  [1 2 3]]] <class 'numpy.ndarray'>
3


In [8]:
y=np.array([[["1"]]])
print(y,type(y))
print(y.ndim)

[[['1']]] <class 'numpy.ndarray'>
3


In [9]:
y=np.array([1,2,3],ndmin=6)
print(y,type(y))
print(y.ndim)

[[[[[[1 2 3]]]]]] <class 'numpy.ndarray'>
6


In [10]:

x=np.array([[[]]])
print(x,type(x))
print(x.ndim)

[] <class 'numpy.ndarray'>
3


In [14]:
#zero filled array


x=np.zeros((4,3))
print(x)
print(type(x))
print(x.ndim)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
2


In [21]:
#zero filled array


x=np.zeros(4)

print(x)
print(type(x))
print(x.ndim)

[0. 0. 0. 0.]
<class 'numpy.ndarray'>
1


In [25]:
#zero filled array


x=np.zeros((4,3))
print(x)
print(type(x))
print(x.ndim)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
2


In [26]:
#zero filled array


x=np.zeros((1,4,4))
print(x)
print(type(x))
print(x.ndim)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<class 'numpy.ndarray'>
3


In [28]:
#ones filled array


x=np.ones((1,4,4))
print(x)
print(type(x))
print(x.ndim)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
<class 'numpy.ndarray'>
3


In [33]:
#arange

x=np.arange(1,10,2)
print(x)

[1 3 5 7 9]


In [34]:
#arange

x=np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
#arange

x=np.arange(1,9.1,2)
print(x)

[1. 3. 5. 7. 9.]


In [51]:
#arange

x=np.array(np.arange(5),ndmin=3)
print(x)

[[[0 1 2 3 4]]]


In [54]:
x=np.array([np.arange(4),np.arange(4,8)])
print(x)

[[0 1 2 3]
 [4 5 6 7]]


In [5]:
import numpy as np

#inspace or linear space

arr=np.linspace(0,10,5)
print(arr)

arr=np.linspace(1,5,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]
[1. 2. 3. 4. 5.]


In [17]:
y=np.linspace(1,2,10)
print(y)

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


In [33]:
y=np.random.rand(4,20)
print(y)

[[0.12675121 0.2984524  0.8772008  0.3620129  0.73337237 0.32570733
  0.65007574 0.79402206 0.97555307 0.62527893 0.36216159 0.81319087
  0.0526032  0.03579924 0.8555015  0.39965153 0.01067115 0.28229955
  0.29572318 0.212157  ]
 [0.44469359 0.02463359 0.41993208 0.3610322  0.25255953 0.57241662
  0.97759728 0.65607076 0.38798692 0.12059473 0.52073832 0.13919632
  0.12525517 0.34515007 0.51474145 0.60266961 0.24139413 0.48070508
  0.70793443 0.96626148]
 [0.19474575 0.91617788 0.30509471 0.04405364 0.55820731 0.66340575
  0.97270618 0.59071682 0.60651223 0.34114599 0.70897011 0.34284991
  0.60046874 0.74690107 0.4582805  0.92077177 0.43345973 0.39610099
  0.77180368 0.88223718]
 [0.77668515 0.75139138 0.81917101 0.14950893 0.15434786 0.91820861
  0.40059237 0.84824932 0.50021215 0.25238309 0.85146364 0.05802644
  0.64361096 0.99239435 0.61341473 0.17312131 0.49700343 0.64546563
  0.61426329 0.62773425]]


# Randint

randint(low,high,size=())

here-- low is inclusive, high is exclusive



In [3]:
import numpy as np
arr=np.random.randint(4)
print(arr)

2


In [4]:
arr1=np.random.randint(1,20,10)
print(arr1)

[17 15  8 15 13  7 18 15  1  9]


In [7]:
arr2=np.random.randint(1,100,size=(2,5,5))
print(arr2)
print(arr2.size)
print(arr2.shape)

[[[80 15 95 70 67]
  [41 47  4 49 38]
  [28 54 28  9 55]
  [ 8 53 38 78 86]
  [49 66 87 82 90]]

 [[ 8 48 63 91 14]
  [39  7 83 63 72]
  [36  7  7 57 56]
  [67 92 63 71 20]
  [81 93 81 26 42]]]
50
(2, 5, 5)


In [11]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,0])
print(arr[0,-1])


5
4


In [20]:
arr=np.array([[[1,2,3,4],[0,9,8,7]]])
print(arr)

[[[1 2 3 4]
  [0 9 8 7]]]


# reshape

reshape(matrix,row,column)



In [9]:
import numpy as np 
arr=np.random.randint(1,100,12)

arr1=arr.reshape(2,3,2)
print(arr1)

[[[19 45]
  [62  9]
  [72 97]]

 [[16 96]
  [93 55]
  [57 79]]]


In [17]:
a=np.random.randint(1,10,27)
a2=a.reshape(3,3,3)
print(a2)

[[[7 9 3]
  [8 6 9]
  [6 1 7]]

 [[8 5 8]
  [4 1 1]
  [1 4 8]]

 [[8 4 5]
  [1 3 4]
  [6 7 8]]]


In [18]:
arr=np.array([1,2,3,4,5])
print(arr)
print()
co=arr.copy()
print(co)

[1 2 3 4 5]

[1 2 3 4 5]


In [19]:
arr=np.array([1,2,3,4,5])

co=arr.view()
print(co)

[1 2 3 4 5]


In [3]:
import numpy as np

arr=np.array([1,2,3,4])
print(arr)

for i in arr:
    print(i)

[1 2 3 4]
1
2
3
4


In [7]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

for i in arr:
    print(i)
    for j in i:
        print(j)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4]
1
2
3
4
[5 6 7 8]
5
6
7
8


In [9]:
arr=np.array([[[1,2,3,4],[5,6,7,8]]])
print("aaray=",arr)

for i in arr:
    print("i=",i)
    for j in i:
        print("j=",j)
        for k in j:
            print("k=",k)

aaray= [[[1 2 3 4]
  [5 6 7 8]]]
i= [[1 2 3 4]
 [5 6 7 8]]
j= [1 2 3 4]
k= 1
k= 2
k= 3
k= 4
j= [5 6 7 8]
k= 5
k= 6
k= 7
k= 8


In [10]:
arr=np.array([[[1,2,3,4],[5,6,7,8]]])
print("aaray=",arr)

for i in np.nditer(arr):
    print(i)

aaray= [[[1 2 3 4]
  [5 6 7 8]]]
1
2
3
4
5
6
7
8


In [11]:
arr=np.array([[[1,2,3,4],[5,6,7,8]]])
print("aaray=",arr)

for i in np.ndenumerate(arr):
    print(i)

aaray= [[[1 2 3 4]
  [5 6 7 8]]]
((0, 0, 0), 1)
((0, 0, 1), 2)
((0, 0, 2), 3)
((0, 0, 3), 4)
((0, 1, 0), 5)
((0, 1, 1), 6)
((0, 1, 2), 7)
((0, 1, 3), 8)


In [19]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

print(arr1)
print()
print(arr2)
print()

arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3]

[4 5 6]

[1 2 3 4 5 6]


In [16]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[4,6],[7,8]])

print(arr1)
print()
print(arr2)
print()

arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2]
 [3 4]]

[[4 6]
 [7 8]]

[[1 2 4 6]
 [3 4 7 8]]


In [17]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[4,6],[7,8]])

print(arr1)
print()
print(arr2)
print()

arr=np.concatenate((arr1,arr2))
print(arr)

[[1 2]
 [3 4]]

[[4 6]
 [7 8]]

[[1 2]
 [3 4]
 [4 6]
 [7 8]]


In [25]:
arr1=np.array([[[1,2],[3,4]]])
arr2=np.array([[[4,6],[7,8]]])

print(arr1)
print()
print(arr2)
print()
               
arr=np.concatenate((arr1,arr2),axis=2)
print(arr)

[[[1 2]
  [3 4]]]

[[[4 6]
  [7 8]]]

[[[1 2 4 6]
  [3 4 7 8]]]


In [28]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])

print(arr1)
print()
print(arr2)
print()

new1=np.stack((arr1,arr2))
print(new1)
print()

new2=np.hstack((arr1,arr2))
print(new2)
print()

new3=np.vstack((arr1,arr2))
print(new3)
print()

new4=np.dstack((arr1,arr2))
print(new4)

[1 2 3 4]

[5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4 5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [29]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])

print(arr1)
print()
print(arr2)
print()


new3=np.vstack((arr1,arr2))
print(new3)
print(new3.shape)
print(new3.size)

[1 2 3 4]

[5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
8
